export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>

        <nav>
          <h1>Navbar</h1>
          <ul>
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href="/tienda">Tienda</a>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  )
}
